const menuData = {
  مشويات: {
    icon: "🔥",
    items: [
      { id: "gr1", name: "فرخة مشوية", price: 340,       desc: "فرخة كاملة مشوية على الفحم بالأصالة",                  img: "images/فرخه مشويه.jpg" },
      { id: "gr2", name: "فراخ تكا", price: 85,          desc: "فراخ تكا مشوية بتتبيلة خاصة",                         img: "images/ربع فرخه تكه.jpg" },
      { id: "gr3", name: "فراخ شيش", price: 85,          desc: "شيش فراخ مشوي على الفحم",                             img: "images/فراخ شيش.jpg" },
      { id: "gr4", name: "كيلو كفته", price: 320,        desc: "كيلو كفته لحم بلدي مشوية",                            img: "images/كيلو كفته.jpg" },
      { id: "gr5", name: "كفته", price: 80,              desc: "كفته لحم مشوية طازجة",                                img: "images/سيخ كفته.jpg" },
      { id: "gr6", name: "سيخ كفته", price: 25,          desc: "سيخ كفته مشوي",                                       img: "images/سيخ كفته.jpg" },
      { id: "gr7", name: "كفته ضاني", price: 90,         desc: "كفته لحم ضاني مشوية",                                 img: "images/سيخ كفته.jpg" },
    ],
  },
  كريب: {
    icon: "🥙",
    items: [ 
      { id: "cr1",  name: "كريب بانيه فريش",         price: 80,  desc: "كريب محشو بانيه فريش مقرمش",                   img: "images/crepe-panee.jpg" },
      { id: "cr2",  name: "كريب كفته",               price: 85,  desc: "كريب محشو كفته مشوية",                         img: "images/crepe-kofta.jpg" },
      { id: "cr3",  name: "كريب برجر",               price: 60,  desc: "كريب محشو برجر",                               img: "images/كريب برجر.webp" },
      { id: "cr4",  name: "كريب كبده",               price: 50,  desc: "كريب محشو كبده اسكندراني",                     img: "images/crepe-kibda.jpg" },
      { id: "cr5",  name: "كريب شيش",                price: 110, desc: "كريب محشو شيش مشوي",                           img: "images/crepe-shish.jpg" },
      { id: "cr6",  name: "كريب بانيه + بطاطس",      price: 90,  desc: "كريب بانيه مع بطاطس",                          img: "images/crepe-panee.jpg" },
      { id: "cr7",  name: "كريب ميكس الهندي",        price: 120, desc: "كريب محشو متنوع",                              img: "images/crepe-mix.jpg" },
      { id: "cr8",  name: "كريب ميكس سوسيس و برجر",  price: 60,  desc: "كريب ميكس سوسيس وبرجر",                        img: "images/crepe-mix.jpg" },
      { id: "cr9",  name: "كريب ميكس اللحوم",        price: 100, desc: "كريب بميكس اللحوم المشكلة",                    img: "images/crepe-mix.jpg" },
      { id: "cr10", name: "كريب سجق",                price: 70,  desc: "كريب محشو سجق",                                img: "images/crepe-soga2.jpg" },
      { id: "cr11", name: "كريب بانيه اضافة قطعة",   price: 100, desc: "كريب بانيه باضافة قطعة اضافية",                img: "images/crepe-panee.jpg" },
      { id: "cr12", name: "كريب فاهيتا",             price: 100, desc: "كريب محشو  فراخ معا قطع الفلفل",               img: "images/crepe-shish.jpg" },
      { id: "cr13", name: "كريب بطاطس",              price: 50,  desc: "كريب محشو بطاطس",                              img: "images/crepe-potato.jpg" },
      { id: "cr14", name: "كريب شاورما",             price: 80,  desc: "كريب محشو شاورما",                             img: "images/crepe-shwrma.jpg" },
    ],
  },
  سندوتشات: {
    icon: "🥪",
    items: [
      { id: "sw1",  name: "ساندوتش كبد",              price: 20,        desc: "ساندوتش كبدة طازجة",                 img: "images/sando-kibda.jpg" },
      { id: "sw2",  name: "ساندوتش سجق فينو",         price: 20,        desc: "ساندوتش سجق فينو",                   img: "images/sando-sigoa.jpg" },
      { id: "sw3",  name: "ساندوتش كفته فينو",        price: 30,        desc: "ساندوتش كفته في خبز فينو",           img: "images/sando-kofta.jpg" },
      { id: "sw4",  name: "ساندوتش   برجر حلواني",    price: 30,        desc: "ساندوتش  برجر حلواني",               img: "images/sando-brgrhlwany.jpg" },
      { id: "sw5",  name: "ساندوتش سماش برجر سنجل",   price: 50,        desc: "ساندوتش سماش برجر سنجل",             img: "images/sando-brgrsmshsingle.jpg" },
      { id: "sw6",  name: "ساندوتش سماش برجر دبل",    price: 80,        desc: "ساندوتش سماش برجر دبل",              img: "images/sando-smashdouble.jpg" },
      { id: "sw7",  name: "ساندوتش بطاطس بلدي",       price: 10,        desc: "ساندوتش بطاطس بلدي",                 img: "images/sando-potatopp.jpg" },
      { id: "sw9",  name: "شاورما فينو",              price: 35,        desc: "شاورما في خبز فينو",                 img: "images/شاورما فينو.jpg" },
      { id: "sw10", name: "شاورما بلدي",              price: 30,        desc: "شاورما في خبز بلدي",                 img: "images/شاورما بلدي.jpg" },
      { id: "sw11", name: "فرايد تشكن سنجل",          price: 50,        desc: "ساندوتش فرايد تشكن",                 img: "images/ساندوتش فرايد تشكن.jpg" },
      { id: "sw12", name: "ساندوتش فرايد تشكن دبل",   price: 70,        desc: "ساندوتش فرايد تشكن دبل",             img: "images/ساندوتش فرايد تشكن دبل.jpg" },
      { id: "sw13", name: "ساندوتش بانيه فريش فينو",  price: 45,        desc: " ساندوتش بانيه فريش فينو",           img: "images/sando-baneh.jpg" },
      { id: "sw14", name: "ساندوتش سجق بلدي",         price: 15,        desc: "ساندوتش سجق بلدي",                   img: "images/sando-sigoapldy.jpg" },
      { id: "sw15", name: "ساندوتش شيش دبل",          price: 80,        desc: "شيش دبل",                            img: "images/sando-shish.jpg" },
      { id: "sw16", name: "ساندوتش شيش فينو",         price: 50,        desc: "شيش في فينو",                        img: "images/sando-shish.jpg" },
      { id: "sw17", name: "ساندوتش برجر حلواني",      price: 30,        desc: "برجر حلواني",                        img: "images/sando-brgrhlwany.jpg" },
      { id: "sw18", name: "ساندوتش فاهيتا فينو",      price: 40,        desc: "فاهيتا فينو",                        img: "images/فاهيتا فينو.jpg" },
      { id: "sw19", name: "ساندوتش بانيه بلدي",       price: 30,        desc: "بانيه في عيش بلدي",                  img: "images/sando-baneh.jpg" },
      { id: "sw20", name: "ساندوتش بطاطس فينو",       price: 15,        desc: "بطاطس في فينو",                      img: "images/ساندوتش بطاطس فينو.jpg" },
      { id: "sw21", name: "ساندوتش   كفته بلدي",      price: 25,        desc: "كفته بلدي ",                         img: "images/كفته بلدي.jpg" },
      { id: "sw22", name: "ساندوتش كفته دبل",         price: 25,        desc: "كفته دبل",                           img: "images/sando-kofta.jpg" },
      { id: "sw23", name: "ساندوتش  برجر حلواني دبل", price: 45,        desc: "كفته دبل",                           img: "images/sando-brgrhlwany.jpg" },
      { id: "sw24", name: "ساندوتش  بطاطس بلدي  ",    price: 10,        desc: "بطاطس بلدي",                         img: "images/sando-potatopp.jpg" },
      { id: "sw25", name: "ساندوتش  برجر محشو ",      price: 45,        desc: "برجر محشو",                          img: "images/برجر محشو.jpg" },



    ],
  },
  حواوشي: {
    icon: "🫓",
    items: [
      { id: "hw1", name: "حواوشي سادة",         price: 15, desc: "حواوشي سادة",             img: "images/hwawshi.jpg"  },
      { id: "hw2", name: "حواوشي سجق",          price: 25, desc: "حواوشي سجق",              img: "images/حواوشي سجق.jpg" },
      { id: "hw3", name: "حواوشي دبل جبنة",     price: 45, desc: "حواوشي دبل مع جبنة",      img: "images/hwawshigbna.jpg" },
      { id: "hw4", name: "حواوشي فراخ",         price: 50, desc: "حواوشي فراخ",             img: "images/حواوشي فراخ.jpg" },
      { id: "hw5", name: "حواوشي كبد وقوانص",   price: 30, desc: "حواوشي كبدة وقوانص",      img: "images/حواوشي كبد وقوانص.jpg" },
      { id: "hw6", name: "حواوشي جبنة",         price: 25, desc: "حواوشي جبنة",             img: "images/hwawshigbna.jpg" },
      { id: "hw7", name: "حواوشي دبل",          price: 35, desc: "حواوشي دبل",              img: "images/hwawshi.jpg" },
    ],
  },
  وجبات: {
    icon: "🍽️",
    items: [
      { id: "wj1", name: "فرايد تشكن",       price: 100,              desc: "وجبة فرايد تشكن كاملة",                                    img: "images/وجبه استربس.jpg"   },
      { id: "wj2", name: "وجبة الهندي",      price: 180,              desc: "الوجبة الخاصة بمطعم الهندي",      badge: "الأكثر طلباً",     img: "images/وجبه الهندي.jpg"   },
      { id: "wj3", name: "وجبة شاورما",      price: 90,               desc: "وجبة شاورما ",                                             img: "images/وجبه شاورما عربي.jpg"  },
      { id: "wj4", name: "وجبة شاورما عربي", price: 120,              desc: "وجبة شاورما عربي",                                         img: "images/وجبه شاورما عربي.jpg"  },
      { id: "wj5", name: "وجبة شيش",         price: 100,              desc: "وجبة شيش مشوي",                                            img: "images/وجبه شيش.jpg"  },
      { id: "wj6", name: "وجبه كاساديا",     price: 120,              desc: "وجبه كاساديا",                                             img: "images/وجبه كاسديا.jpg"  },
      { id: "wj7", name: "طلب كبدة كاملة",   price: 70,               desc: "طلب كبدة اسكندراني كامل",                                  img: "images/طلب كبده.jpg"  },
    ],
     },
 السوري: {
    icon: "🍽️",
    items: [
      { id: "M1", name: "ساندوتش بطاطس سوري",                  price: 25,                    desc: "ساندوتش بطاطس سوري",                                                 img: "images/ساندوتش سوري.jpg"   },
      { id: "M2", name: "ساندوتش شاورما سوري",                 price: 40,                    desc: "ساندوتش شاورما سوري",       badge: "الأكثر طلباً",                     img: "images/شاورما سوري.jpg"   },
      { id: "M3", name: "ساندوتش كفته سوري",                   price: 35,                    desc: "ساندوتش كفته سوري",                                                  img: "images/كفته سوري.jpg"  },
      { id: "M4", name: "ساندوتش سجق سوري ",                   price: 35,                   desc: "ساندوتش سجق سوري",                                                    img: "images/سوري سجق.jpg"  },
      { id: "M5", name: " ساندوتش فاهيتا سوري",                price: 60,                  desc: "ساندوتش فاهيتا سوري",                                                  img: "images/فاهيتا سوري.jpg"  },
      { id: "M6", name: " ساندوتش كبده سوري",                  price: 35,                 desc: "ساندوتش كبده سوري",                                                     img: "images/كبده سوري.jpg"  },
      { id: "M7", name: " ساندوتش شيش سوري",                   price: 60,                  desc: "ساندوتش شيش سوري",                                                      img: "images/فاهيتا سوري.jpg"  },
      { id: "M9", name: " ساندوتش بانيه+بطاطس سوري",           price: 45,                desc: "ساندوتش بانيه+بطاطس سوري",                                                 img: "images/سوري بانيه.jpg"  },


    ],
  },
  بروست: {
    icon: "🍗",
    comingSoon: true,
    items: [],
  },
  باستا: {
    icon: "🍝",
    comingSoon: true,
    items: [],
  },
};
